### PR TITLE
Implemented 'ODataPropertyName' attribute

### PR DESCRIPTION
**Pull request by pikami**
There may be cases when the model in the OData service is different from the model in the application. In those cases we need a way to override the property names of our model to match those in the OData service.
This PR adds support for custom property names during query building by using a new 'ODataPropertyName' attribute.

This fixes and or provides workarounds the following issues:
* https://github.com/ZEXSM/OData.QueryBuilder/issues/115
* https://github.com/ZEXSM/OData.QueryBuilder/issues/99

While I believe this feature can be beneficial in certain scenarios, I do acknowledge that it may not be the most elegant or intuitive solution. I'm more than open to discussing alternative approaches that might better align with this library's design philosophy.

### CODE REVIEW

**Comment by BarberMSFT** [comment]
will this get approved?

**Comment by pikami** [comment]
> will this get approved?

@BarberMSFT I've published my patched version to nuget, you can use it while this PR is not merged.
https://www.nuget.org/packages/OData.BigQueryBuilder

**Comment by ZEXSM** [comment]
> > will this get approved?
> 
> @BarberMSFT I've published my patched version to nuget, you can use it while this PR is not merged. https://www.nuget.org/packages/OData.BigQueryBuilder

**Comment by pikami** [comment]
@ZEXSM Looks like your ci pipeline doesn't have the "CONFIGURATION" variable set.

**Comment by ZEXSM** [comment]
@pikami,  checked, she is there, I'm still figuring out what the problem is

**Review by ZEXSM — APPROVED** [review]

**Comment by ZEXSM** [comment]
@pikami try

**Comment by pikami** [comment]
@ZEXSM Just checked, it works as expected.

**Comment by ZEXSM** [comment]
@pikami,  try merge PR

**Comment by pikami** [comment]
Only those with write access can merge pull requests.

**Comment by BarberMSFT** [comment]
was out last week but awesome work, thank you!

**Pull request merged**
